name: cv_app
description: A new Flutter project.
publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  cupertino_icons: ^1.0.2
  equatable: ^2.0.5
  file_picker: ^5.2.10
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  # flutter_screenutil: ^5.7.0
  get_it: ^7.6.4
  image_picker: ^0.8.7+4
  path_provider: ^2.0.14
  pdf: ^3.10.1
  screenshot: ^2.1.0
  share_plus: ^7.2.1
  sqflite: ^2.2.7

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true
  assets:
    - assets/image/
